public enum ItemID
{
    RED_ROCK, STONE_BLOCK, ICE,
    OXYGEN_BACTERIA_FOSSIL, NITROGEN_BACTERIA_FOSSIL, CARBON_DIOXIDE_BACTERIA_FOSSIL,
    GRASS_FOSSIL, TREE_FOSSIL, ANIMAL_FOSSIL,
    OXYGEN_BACTERIA_VIAL, NITROGEN_BACTERIA_VIAL, CARBON_DIOXIDE_BACTERIA_VIAL,
    GRASS, TREE,
    CHOCOLATE, CAKE, WATER
}
