public enum ItemID
{
    RED_ROCK, STONE_BLOCK, ICE,
    OXYGEN_BACTERIA_FOSSIL, NITROGEN_BACTERIA_FOSSIL, CARBON_DIOXIDE_BACTERIA_FOSSIL,
    GRASS_FOSSIL, TREE_FOSSIL, WHEAT_FOSSIL,
    FROG_FOSSIL, REGULAR_ANIMAL_FOSSIL, BIG_ANIMAL_FOSSIL,
    OXYGEN_BACTERIA_VIAL, NITROGEN_BACTERIA_VIAL, CARBON_DIOXIDE_BACTERIA_VIAL,
    GRASS, TREE, WHEAT,
    FROG_EGG, REGULAR_EGG, BIG_EGG,
    CHOCOLATE, CAKE, WATER, MEAT
}
